#! /bin/bash  # <-- to trick vs code
##### KEYBINDS ######
##
##
	# Super in Mod4 and Alt is Mod1
	set $super Mod4
	set $alt Mod1
	set $mod Mod4

	# Navigation
		# Move your focus around
		bindsym $super+Left focus left
		bindsym $super+Down focus down
		bindsym $super+Up focus up
		bindsym $super+Right focus right
		# Move the focused window with the same, but add Shift
		bindsym $super+Shift+Left move left
		bindsym $super+Shift+Down move down
		bindsym $super+Shift+Up move up
		bindsym $super+Shift+Right move right
		# set workspace names & variables
        set $ws1 "1"
        set $ws2 "2"
        set $ws3 "3"
        set $ws4 "4"
        set $ws5 "5"
        set $ws6 "6"
        set $ws7 "7"
        set $ws8 "8"
        set $ws9 "9"
        set $ws10 "10"
        # switch to workspace
        # bindsym $mod+1 workspace number $ws1
        # bindsym $mod+2 workspace number $ws2
        # bindsym $mod+3 workspace number $ws3
        # bindsym $mod+4 workspace number $ws4
        # bindsym $mod+5 workspace number $ws5
        # bindsym $mod+6 workspace number $ws6
        # bindsym $mod+7 workspace number $ws7
        # bindsym $mod+8 workspace number $ws8
        # bindsym $mod+9 workspace number $ws9
        # bindsym $mod+0 workspace number $ws10
		bindsym $mod+1 exec ~/.config/i3/empty_workspace_launcher.sh 1 ~/.config/rofi/super_menu.sh
        bindsym $mod+2 exec ~/.config/i3/empty_workspace_launcher.sh 2 ~/.config/rofi/super_menu.sh
        bindsym $mod+3 exec ~/.config/i3/empty_workspace_launcher.sh 3 ~/.config/rofi/super_menu.sh
        bindsym $mod+4 exec ~/.config/i3/empty_workspace_launcher.sh 4 ~/.config/rofi/super_menu.sh
        bindsym $mod+5 exec ~/.config/i3/empty_workspace_launcher.sh 5 ~/.config/rofi/super_menu.sh
        bindsym $mod+6 exec ~/.config/i3/empty_workspace_launcher.sh 6 ~/.config/rofi/super_menu.sh
        bindsym $mod+7 exec ~/.config/i3/empty_workspace_launcher.sh 7 ~/.config/rofi/super_menu.sh
        bindsym $mod+8 exec ~/.config/i3/empty_workspace_launcher.sh 8 ~/.config/rofi/super_menu.sh
        bindsym $mod+9 exec ~/.config/i3/empty_workspace_launcher.sh 9 ~/.config/rofi/super_menu.sh
        bindsym $mod+0 exec ~/.config/i3/empty_workspace_launcher.sh 10 ~/.config/rofi/super_menu.sh
        # move focused container to workspace
        bindsym $mod+Shift+1 move container to workspace number $ws1
        bindsym $mod+Shift+2 move container to workspace number $ws2
        bindsym $mod+Shift+3 move container to workspace number $ws3
        bindsym $mod+Shift+4 move container to workspace number $ws4
        bindsym $mod+Shift+5 move container to workspace number $ws5
        bindsym $mod+Shift+6 move container to workspace number $ws6
        bindsym $mod+Shift+7 move container to workspace number $ws7
        bindsym $mod+Shift+8 move container to workspace number $ws8
        bindsym $mod+Shift+9 move container to workspace number $ws9
        bindsym $mod+Shift+0 move container to workspace number $ws10
		# Move focus to the parent container
		bindsym $super+a focus parent  # bindsym $mod+d focus child

		# tab through workspaces
		bindsym $mod+Tab workspace next
		bindsym $mod+Shift+Tab workspace prev
		bindsym $mod+asciicircum exec ~/.config/i3/new_workspace.py
		bindsym $mod+Escape workspace back_and_forth
		bindsym $alt+Tab exec rofi -show "window" &

	# Kill focused window
	bindsym $super+Shift+q kill
	bindsym $alt+F4 kill

	# Drag floating windows with modifier pressed
	floating_modifier $alt

	# Reload configuration
	bindsym $super+Shift+r reload
	bindsym $super+Control+r restart


	# Tiling
		# bindsym $super+s layout stacking
		bindsym $super+t layout tabbed
		bindsym $super+e layout toggle split
		bindsym $super+h splith
		bindsym $super+v splitv
		bindsym $super+f fullscreen

	# Floating
		bindsym $super+Shift+space floating toggle
		# Swap focus between the tiling area and the floating area
		bindsym $super+space focus mode_toggle


	# Resize windows
		mode "resize" {
	    # left will shrink the containers width
	    # right will grow the containers width
	    # up will shrink the containers height
	    # down will grow the containers height
	    bindsym Left resize shrink width 250px
		bindsym Shift+Left resize shrink width 10px
	    bindsym Down resize grow height 250px
		bindsym Shift+Down resize grow height 10px
	    bindsym Up resize shrink height 250px
		bindsym Shift+Up resize shrink height 10px
	    bindsym Right resize grow width 250px
		bindsym Shift+Right resize grow width 10px

	    # Return to default mode
	    bindsym Return mode "default"
	    bindsym Escape mode "default"
		}
		bindsym $super+r mode "resize"
	
	bindsym $mod+Ctrl+Left resize shrink width 100px
	bindsym $mod+Ctrl+Down resize grow height 100px
	bindsym $mod+Ctrl+Up resize shrink height 100px
	bindsym $mod+Ctrl+Right resize grow width 100px

###### Screenshot directory ######
##
##
	exec --no-startup-id mkdir -p $HOME/Pictures/Screenshots &

###### THEME ######
##
##

	# Font
	font pango:Iosevka Extended Bold 10


	title_align center
	focus_follows_mouse false

	# Borders
		default_floating_border pixel 1
		default_border pixel 1
		hide_edge_borders smart # no borders if only one window on workspace

	# Colors
		# class                 border  bground text    indicator child_border
		client.focused          #C50ED2 #000000 #FFFFFF #C50ED2   #EF11FF
		client.focused_inactive #333333 #5F676A #FFFFFF #484E50   #5F676A
		client.unfocused        #222222 #000000 #888888 #292D2E   #222222
		client.urgent           #C50ED2 #EF11FF #FFFFFF #EF11FF   #EF11FF
		client.placeholder      #000000 #0C0C0C #FFFFFF #000000   #0C0C0C
		client.background       #FFFFFF

###### Load Xresources file ######
##
##
    # exec --no-startup-id $HOME/.config/scripts/actions/load_x_prop.sh




###### STATUSBAR ######
##
##

	bar {
	    # position top
	    # font pango:Iosevka Extended Bold 10
	    # tray_output none
	    # height 28

	    # When the status_command prints a new line to stdout, swaybar updates.
	    # The default just shows the current date and time.
	    status_command i3blocks

		colors {
			background #000000
			statusline #FFFFFF
			separator  #666666

			focused_workspace  #C50ED2 #C50ED2 #FFFFFF
			active_workspace   #333333 #222222 #FFFFFF
			inactive_workspace #333333 #222222 #888888
			urgent_workspace   #FF435E #FF435E #FFFFFF
			binding_mode       #FF435E #FF435E #FFFFFF
		}
	}

	# hide/unhide i3status bar
	bindsym $mod+m bar mode toggle






###### SHORTCUTS ######
##
##
	# Terminal
	bindsym $super+Return exec --no-startup-id i3-sensible-terminal &

	# File manager
	bindsym $super+Shift+f exec --no-startup-id xst -e ranger &

	# Brightness
	bindsym XF86MonBrightnessDown exec --no-startup-id ~/.config/scripts/notify/light_down.sh && pkill -RTMIN+20 i3blocks
	bindsym XF86MonBrightnessUp exec --no-startup-id ~/.config/scripts/notify/light_up.sh && pkill -RTMIN+20 i3blocks
	
	# Audio
	exec --no-startup-id pamixer --set-volume 40 -m # this mutes sound on startup and sets sound to 40
	exec --no-startup-id pasystray & # volumeicon
	bindsym XF86AudioRaiseVolume exec --no-startup-id ~/.config/scripts/notify/volume_plus.sh && pkill -RTMIN+30 i3blocks
	bindsym XF86AudioLowerVolume exec --no-startup-id ~/.config/scripts/notify/volume_minus.sh && pkill -RTMIN+30 i3blocks
	bindsym XF86AudioMute exec --no-startup-id ~/.config/scripts/notify/volume_mute.sh && pkill -RTMIN+30 i3blocks
	# bindsym XF86AudioRaiseVolume exec amixer -q sset Master 5%+ unmute
	# bindsym XF86AudioLowerVolume  exec amixer -q sset Master 5%- unmute
	# bindsym XF86AudioMute exec amixer -q sset Master togglebindsym $mod+= exec amixer -q sset Master 5%+ unmute
	# bindsym $mod+- exec amixer -q sset Master 5%- unmutebindsym $mod+x [urgent=latest] focus# num lock activated
	# Media player controls
	# bindsym XF86AudioPlay exec playerctl play-pause
	# bindsym XF86AudioPause exec playerctl play-pause
	bindsym XF86AudioPlay exec playerctl play-pause
	bindsym XF86AudioNext exec playerctl next
	bindsym XF86AudioPrev exec playerctl previous

	# Screenshot
	bindsym Print exec --no-startup-id ~/.config/scripts/screenshot/i3_screen.sh &
	bindsym $super+Print exec --no-startup-id ~/.config/scripts/screenshot/i3_active.sh &
	bindsym Shift+Print exec --no-startup-id ~/.config/scripts/screenshot/i3_region.sh &
	
	# Launcher
	
	bindsym --release Super_L exec --no-startup-id ~/.config/rofi/super_menu.sh &
	bindsym $mod+d exec "dmenu_run -nf '#BBBBBB' -nb '#222222' -sb '#EF11FF' -sf '#000000' -fn 'monospace-16' -p 'run: '"
	# bindsym $mod+d exec "rofi -modi drun,run -show drun"

	# Scan Wifi
	# bindsym $super+Shift+w exec --no-startup-id nmcli device wifi rescan &
	
	# Screen lock
	bindsym $super+l exec --no-startup-id ~/.config/scripts/actions/i3lock.sh &
	# bindsym $super+Shift+l exec --no-startup-id ~/.config/scripts/actions/i3lock_sleep.sh &  # sleep&hibernation not working on my pc


##### INPUT #####
##
##
	exec --no-startup-id $HOME/.config/scripts/actions/configureXorgTouchpad.sh &



###### AUTOSTART APPLICATIONS ######
##
##
		exec --no-startup-id dunst & # notification manager
        # exec firefox &
		exec --no-startup-id i3-msg 'workspace 1; exec /usr/bin/firefox' &
        exec --no-startup-id autorandr --change & # for automatic display (profile) detection
		# exec code &
		exec --no-startup-id nm-applet & # networkmanager
		# exec --no-startup-id compton --config ~/.config/i3/compton.conf & #for transparency of terminal 
        exec --no-startup-id ( sleep 1 && feh --bg-scale ~/.wallpaper.jpg ) &
		# exec guake &
		

# autoconfigure apps 
	# Note: My keyboard has dedicated buttons that it is mapped to alsamixer
	# assign [class="^Firefox$"] 1
	# assign [class="^Slack$"] 3
	# assign [class="^Code$"] 2
	for_window [class = "^Code"] layout tabbed
	# assign [class="^Vlc$"] 9
	assign [class="^Spotify$"] 10
	for_window [class="Spotify"] move to workspace $ws10
	# for_window [class="^Slack$"] floating enable

	# Use Mouse+$mod to drag floating windows to their wanted position
	for_window [window_role="pop-up"] floating enable
	for_window [window_role="task_dialog"] floating enable # Key bind for Alsa sound


# clipboard
    bindsym $mod+c exec rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
    bindsym $mod+Shift+c exec greenclip clear
    exec greenclip daemon # clipboard manager

	# color-picker
	bindsym --release $mod+Shift+p exec xcolor | xclip -selection clipboard

 
# Restart or shutdown or suspend by using WinKey+Pause key with meny to select option
	set $mode_system System (l) lock, (e) logout, (Shift+s) suspend, (h) hibernate, (r) reboot, (s) shutdown
	mode "$mode_system" {
		bindsym l exec --no-startup-id $Locker, mode "default"
		bindsym e exec --no-startup-id i3-msg exit, mode "default"
		# bindsym Shift+s exec --no-startup-id $Locker && systemctl suspend, mode "default"
		# bindsym h exec --no-startup-id $Locker && systemctl hibernate, mode "default"
		bindsym r exec --no-startup-id systemctl reboot, mode "default"
		bindsym s exec --no-startup-id systemctl poweroff -i, mode "default" # back to normal: Enter or Escape
		bindsym Return mode "default"
		bindsym Escape mode "default"
	}
	bindsym $mod+Pause mode "$mode_system" 

# App Icons   (requires `i3/util.py` file)
	exec_always ~/.config/i3/autoname_workspaces.py --norenumber_workspaces &
